[2024-12-29T16:17:30.499+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-29T16:17:30.566+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T16:17:29.283208+00:00 [queued]>
[2024-12-29T16:17:30.624+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T16:17:29.283208+00:00 [queued]>
[2024-12-29T16:17:30.643+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-29T16:17:30.684+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2024-12-29 16:17:29.283208+00:00
[2024-12-29T16:17:30.690+0000] {standard_task_runner.py:63} INFO - Started process 2799 to run task
[2024-12-29T16:17:30.695+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'manual__2024-12-29T16:17:29.283208+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpzkotbcbz']
[2024-12-29T16:17:30.698+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask extract.extract_and_load_to_staging
[2024-12-29T16:17:30.792+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T16:17:29.283208+00:00 [running]> on host 52712ca165cb
[2024-12-29T16:17:30.961+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T16:17:29.283208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T16:17:29.283208+00:00'
[2024-12-29T16:17:30.962+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-29T16:17:31.225+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-12-29T16:17:34.807+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database
[2024-12-29T16:17:34.814+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-12-29T16:17:37.954+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-29T16:17:37.955+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 30, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 15, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown server host 'mysql' (-2)")
[2024-12-29T16:17:37.972+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=manual__2024-12-29T16:17:29.283208+00:00, execution_date=20241229T161729, start_date=20241229T161730, end_date=20241229T161737
[2024-12-29T16:17:38.017+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task extract.extract_and_load_to_staging ((2005, "Unknown server host 'mysql' (-2)"); 2799)
[2024-12-29T16:17:38.084+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-29T16:17:38.146+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
