[2025-01-09T15:24:21.405+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-09T15:24:21.508+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-01-09T15:24:20.788968+00:00 [queued]>
[2025-01-09T15:24:21.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-01-09T15:24:20.788968+00:00 [queued]>
[2025-01-09T15:24:21.535+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-09T15:24:21.577+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-01-09 15:24:20.788968+00:00
[2025-01-09T15:24:21.585+0000] {standard_task_runner.py:63} INFO - Started process 423 to run task
[2025-01-09T15:24:21.591+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'manual__2025-01-09T15:24:20.788968+00:00', '--job-id', '916', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpo79ok_0x']
[2025-01-09T15:24:21.598+0000] {standard_task_runner.py:91} INFO - Job 916: Subtask extract.extract_and_load_to_staging
[2025-01-09T15:24:21.700+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-01-09T15:24:20.788968+00:00 [running]> on host 683e2530fb40
[2025-01-09T15:24:22.301+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-01-09T15:24:20.788968+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-09T15:24:20.788968+00:00'
[2025-01-09T15:24:22.303+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-09T15:24:22.358+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-01-09T15:24:43.454+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database
[2025-01-09T15:24:43.475+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-01-09T15:25:04.501+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-09T15:25:04.506+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 30, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 15, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on '192.168.1.149' (115)")
[2025-01-09T15:25:04.540+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-01-09T15:24:20.788968+00:00, execution_date=20250109T152420, start_date=20250109T152421, end_date=20250109T152504
[2025-01-09T15:25:04.564+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 916 for task extract.extract_and_load_to_staging ((2002, "Can't connect to server on '192.168.1.149' (115)"); 423)
[2025-01-09T15:25:04.606+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-09T15:25:04.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
