[2025-01-06T15:23:05.882+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-06T15:23:05.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-06T15:23:05.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-06T15:23:05.987+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-06T15:23:06.141+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-01-02 00:00:00+00:00
[2025-01-06T15:23:06.150+0000] {standard_task_runner.py:63} INFO - Started process 215 to run task
[2025-01-06T15:23:06.166+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-01-02T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpsilko_a5']
[2025-01-06T15:23:06.172+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask extract.extract_and_load_to_staging
[2025-01-06T15:23:06.307+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-01-02T00:00:00+00:00 [running]> on host 1f482c49ea2b
[2025-01-06T15:23:06.862+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T00:00:00+00:00'
[2025-01-06T15:23:06.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-06T15:23:07.286+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-01-06T15:23:10.830+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database
[2025-01-06T15:23:10.837+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-01-06T15:23:13.958+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-06T15:23:13.959+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 30, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 15, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown server host 'mysql' (-2)")
[2025-01-06T15:23:13.982+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-01-02T00:00:00+00:00, execution_date=20250102T000000, start_date=20250106T152305, end_date=20250106T152313
[2025-01-06T15:23:14.021+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task extract.extract_and_load_to_staging ((2005, "Unknown server host 'mysql' (-2)"); 215)
[2025-01-06T15:23:14.033+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-06T15:23:14.068+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-06T15:23:14.077+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
