[2025-01-06T15:23:04.273+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:04.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:23:04.276+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:23:04.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:04.312+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:23:04.305+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:23:04.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:04.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.084 seconds
[2025-01-06T15:23:34.675+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:34.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:23:34.679+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:23:34.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:34.718+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:23:34.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:23:34.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:34.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.101 seconds
[2025-01-06T15:23:58.068+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:58.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:23:58.073+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:23:58.072+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:58.118+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:23:58.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:23:58.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:23:58.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.091 seconds
[2025-01-06T15:24:28.532+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:24:28.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:24:28.535+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:24:28.535+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:24:28.560+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:24:28.555+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:24:28.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:24:28.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.062 seconds
[2025-01-06T15:24:51.982+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:24:51.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:24:51.985+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:24:51.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:24:52.011+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:24:52.006+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:24:52.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:24:52.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.058 seconds
[2025-01-06T15:25:12.358+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:25:12.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:25:12.361+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:25:12.361+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:25:12.400+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:25:12.395+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:25:12.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:25:12.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.076 seconds
[2025-01-06T15:26:38.953+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:26:38.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:26:38.961+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:26:38.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:26:39.037+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:26:39.020+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:26:39.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:26:39.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.179 seconds
[2025-01-06T15:27:09.236+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:27:09.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:27:09.240+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:27:09.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:27:09.277+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:27:09.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:27:09.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:27:09.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.122 seconds
[2025-01-06T15:27:39.751+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:27:39.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:27:39.756+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:27:39.756+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:27:39.786+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:27:39.781+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:27:39.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:27:39.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.086 seconds
[2025-01-06T15:28:10.228+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:28:10.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:28:10.230+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:28:10.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:28:10.250+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:28:10.245+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:28:10.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:28:10.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.054 seconds
[2025-01-06T15:28:40.826+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:28:40.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:28:40.835+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:28:40.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:28:40.895+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:28:40.873+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:28:40.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:28:40.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.152 seconds
[2025-01-06T15:29:11.365+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:29:11.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:29:11.368+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:29:11.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:29:11.405+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:29:11.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:29:11.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:29:11.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.093 seconds
[2025-01-06T15:29:42.030+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:29:42.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:29:42.035+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:29:42.034+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:29:42.065+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:29:42.059+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:29:42.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:29:42.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.081 seconds
[2025-01-06T15:30:12.474+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:30:12.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:30:12.477+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:30:12.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:30:12.496+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:30:12.492+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:30:12.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:30:12.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.055 seconds
[2025-01-06T15:30:42.906+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:30:42.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:30:42.910+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:30:42.909+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:30:42.943+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:30:42.936+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:30:42.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:30:42.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.076 seconds
[2025-01-06T15:31:13.354+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:31:13.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:31:13.356+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:31:13.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:31:13.384+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:31:13.378+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:31:13.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:31:13.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.071 seconds
[2025-01-06T15:31:43.973+0000] {processor.py:161} INFO - Started process (PID=402) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:31:43.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:31:43.976+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:31:43.976+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:31:44.016+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:31:44.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:31:44.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:31:44.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.093 seconds
[2025-01-06T15:32:14.439+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:32:14.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:32:14.441+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:32:14.441+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:32:14.478+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:32:14.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:32:14.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:32:14.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.076 seconds
[2025-01-06T15:32:44.891+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:32:44.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:32:44.893+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:32:44.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:32:44.915+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:32:44.910+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:32:44.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:32:44.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.054 seconds
[2025-01-06T15:33:15.317+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:33:15.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:33:15.321+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:33:15.321+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:33:15.352+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:33:15.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:33:15.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:33:15.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.074 seconds
[2025-01-06T15:33:45.771+0000] {processor.py:161} INFO - Started process (PID=486) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:33:45.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:33:45.776+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:33:45.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:33:45.807+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:33:45.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:33:45.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:33:45.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.072 seconds
[2025-01-06T15:34:16.310+0000] {processor.py:161} INFO - Started process (PID=507) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:34:16.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:34:16.313+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:34:16.313+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:34:16.344+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:34:16.338+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:34:16.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:34:16.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.069 seconds
[2025-01-06T15:34:46.820+0000] {processor.py:161} INFO - Started process (PID=528) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:34:46.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:34:46.822+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:34:46.822+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:34:46.856+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:34:46.849+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:34:46.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:34:46.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.084 seconds
[2025-01-06T15:35:17.581+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:35:17.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:35:17.585+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:35:17.584+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:35:17.614+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:35:17.607+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:35:17.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:35:17.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.080 seconds
[2025-01-06T15:35:48.195+0000] {processor.py:161} INFO - Started process (PID=571) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:35:48.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:35:48.198+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:35:48.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:35:48.224+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:35:48.218+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:35:48.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:35:48.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.065 seconds
[2025-01-06T15:36:18.787+0000] {processor.py:161} INFO - Started process (PID=592) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:36:18.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:36:18.790+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:36:18.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:36:18.811+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:36:18.806+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:36:18.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:36:18.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.055 seconds
[2025-01-06T15:36:49.354+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:36:49.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:36:49.357+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:36:49.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:36:49.382+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:36:49.377+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:36:49.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:36:49.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.063 seconds
[2025-01-06T15:37:19.779+0000] {processor.py:161} INFO - Started process (PID=634) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:37:19.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:37:19.781+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:37:19.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:37:19.802+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:37:19.798+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:37:19.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:37:19.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.053 seconds
[2025-01-06T15:37:50.195+0000] {processor.py:161} INFO - Started process (PID=655) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:37:50.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:37:50.198+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:37:50.197+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:37:50.218+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:37:50.213+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:37:50.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:37:50.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.053 seconds
[2025-01-06T15:38:20.591+0000] {processor.py:161} INFO - Started process (PID=676) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:38:20.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:38:20.594+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:38:20.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:38:20.613+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:38:20.608+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:38:20.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:38:20.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.050 seconds
[2025-01-06T15:38:50.999+0000] {processor.py:161} INFO - Started process (PID=697) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:38:51.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:38:51.003+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:38:51.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:38:51.024+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:38:51.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:38:51.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:38:51.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.059 seconds
[2025-01-06T15:39:21.409+0000] {processor.py:161} INFO - Started process (PID=718) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:39:21.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:39:21.413+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:39:21.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:39:21.445+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:39:21.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:39:21.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:39:21.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.073 seconds
[2025-01-06T15:39:51.866+0000] {processor.py:161} INFO - Started process (PID=739) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:39:51.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:39:51.872+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:39:51.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:39:51.911+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:39:51.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:39:51.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:39:51.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.104 seconds
[2025-01-06T15:40:22.333+0000] {processor.py:161} INFO - Started process (PID=760) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:40:22.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:40:22.335+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:40:22.335+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:40:22.360+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:40:22.355+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:40:22.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:40:22.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.061 seconds
[2025-01-06T15:40:53.060+0000] {processor.py:161} INFO - Started process (PID=781) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:40:53.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:40:53.064+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:40:53.064+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:40:53.094+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:40:53.088+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:40:53.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:40:53.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.079 seconds
[2025-01-06T15:41:23.491+0000] {processor.py:161} INFO - Started process (PID=802) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:41:23.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:41:23.493+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:41:23.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:41:23.516+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:41:23.509+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:41:23.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:41:23.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.058 seconds
[2025-01-06T15:41:54.087+0000] {processor.py:161} INFO - Started process (PID=823) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:41:54.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:41:54.092+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:41:54.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:41:54.113+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:41:54.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:41:54.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:41:54.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.056 seconds
[2025-01-06T15:42:24.539+0000] {processor.py:161} INFO - Started process (PID=844) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:42:24.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:42:24.543+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:42:24.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:42:24.570+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:42:24.564+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:42:24.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:42:24.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.079 seconds
[2025-01-06T15:42:54.979+0000] {processor.py:161} INFO - Started process (PID=865) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:42:54.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:42:54.982+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:42:54.981+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:42:55.007+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:42:55.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:42:55.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:42:55.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.060 seconds
[2025-01-06T15:43:25.491+0000] {processor.py:161} INFO - Started process (PID=886) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:43:25.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:43:25.493+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:43:25.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:43:25.512+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:43:25.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:43:25.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:43:25.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.051 seconds
[2025-01-06T15:43:55.935+0000] {processor.py:161} INFO - Started process (PID=907) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:43:55.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:43:55.936+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:43:55.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:43:55.955+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:43:55.951+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:43:55.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:43:55.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.048 seconds
[2025-01-06T15:44:26.339+0000] {processor.py:161} INFO - Started process (PID=928) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:44:26.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:44:26.341+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:44:26.341+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:44:26.361+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:44:26.357+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:44:26.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:44:26.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.053 seconds
[2025-01-06T15:44:56.859+0000] {processor.py:161} INFO - Started process (PID=949) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:44:56.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:44:56.863+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:44:56.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:44:56.882+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:44:56.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:44:56.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:44:56.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.054 seconds
[2025-01-06T15:45:27.347+0000] {processor.py:161} INFO - Started process (PID=970) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:45:27.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:45:27.350+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:45:27.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:45:27.380+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:45:27.373+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:45:27.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:45:27.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.070 seconds
[2025-01-06T15:45:57.780+0000] {processor.py:161} INFO - Started process (PID=991) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:45:57.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:45:57.783+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:45:57.782+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:45:57.816+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:45:57.806+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:45:57.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:45:57.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.080 seconds
[2025-01-06T15:46:28.262+0000] {processor.py:161} INFO - Started process (PID=1012) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:46:28.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:46:28.265+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:46:28.264+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:46:28.303+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:46:28.293+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:46:28.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:46:28.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.079 seconds
[2025-01-06T15:46:58.879+0000] {processor.py:161} INFO - Started process (PID=1033) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:46:58.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:46:58.884+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:46:58.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:46:58.916+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:46:58.909+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:46:58.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:46:58.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.073 seconds
[2025-01-06T15:47:29.466+0000] {processor.py:161} INFO - Started process (PID=1054) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:47:29.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:47:29.469+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:47:29.469+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:47:29.502+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:47:29.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:47:29.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:47:29.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.075 seconds
[2025-01-06T15:47:59.930+0000] {processor.py:161} INFO - Started process (PID=1075) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:47:59.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:47:59.933+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:47:59.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:47:59.963+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:47:59.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:47:59.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:47:59.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.066 seconds
[2025-01-06T15:48:30.406+0000] {processor.py:161} INFO - Started process (PID=1096) to work on /opt/airflow/dags/dag_test.py
[2025-01-06T15:48:30.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2025-01-06T15:48:30.409+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:48:30.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2025-01-06T15:48:30.434+0000] {logging_mixin.py:188} INFO - [2025-01-06T15:48:30.429+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 27, in <module>
    training_model = [
  File "/opt/airflow/dags/dag_test.py", line 28, in <listcomp>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 220, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 893, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'training_model_B,' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-06T15:48:30.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2025-01-06T15:48:30.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.063 seconds
