[2024-12-29T16:11:51.771+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-29T16:11:51.828+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T16:11:51.090395+00:00 [queued]>
[2024-12-29T16:11:51.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T16:11:51.090395+00:00 [queued]>
[2024-12-29T16:11:51.844+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-29T16:11:51.899+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2024-12-29 16:11:51.090395+00:00
[2024-12-29T16:11:51.907+0000] {standard_task_runner.py:63} INFO - Started process 2610 to run task
[2024-12-29T16:11:51.912+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'manual__2024-12-29T16:11:51.090395+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmph_edmfdi']
[2024-12-29T16:11:51.915+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask extract.extract_and_load_to_staging
[2024-12-29T16:11:51.992+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2024-12-29T16:11:51.090395+00:00 [running]> on host 52712ca165cb
[2024-12-29T16:11:52.160+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T16:11:51.090395+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T16:11:51.090395+00:00'
[2024-12-29T16:11:52.162+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-29T16:11:52.498+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-12-29T16:11:52.533+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database
[2024-12-29T16:11:52.545+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-12-29T16:11:52.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-29T16:11:52.561+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 30, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 15, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user '***'@'localhost' (using password: YES)")
[2024-12-29T16:11:52.586+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=manual__2024-12-29T16:11:51.090395+00:00, execution_date=20241229T161151, start_date=20241229T161151, end_date=20241229T161152
[2024-12-29T16:11:52.618+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 85 for task extract.extract_and_load_to_staging ((1045, "Access denied for user '***'@'localhost' (using password: YES)"); 2610)
[2024-12-29T16:11:52.663+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-29T16:11:52.711+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-29T16:11:52.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
